version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: cd_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cd_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/configs/import.sql:/docker-entrypoint-initdb.d/init_db.sql

  backend:
    build: ./server
    container_name: cd_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: cd_database
      DB_HOST: localhost
      DB_PORT: 5432
      PORT: 5005
    ports:
      - "5005:5005"

  frontend:
    build: ./client
    container_name: cd_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data: