version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: cd_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cd_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./server/configs/import.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgres_dev_data: